include: package:flutter_lints/flutter.yaml

formatter:
  page_width: 120
  trailing_commas: preserve

linter:
  rules:
    - always_declare_return_types
    - always_put_control_body_on_new_line
    - cancel_subscriptions
    - prefer_single_quotes
    - eol_at_end_of_file
    - prefer_const_constructors
    - prefer_const_declarations
    - prefer_const_literals_to_create_immutables

analyzer:
  language:
    strict-casts: true
    strict-raw-types: true
    strict-inference: true
  errors:
    body_might_complete_normally_nullable: error
    collection_methods_unrelated_type: error
    pattern_never_matches_value_type: error
    prefer_typing_uninitialized_variables: error
